### ISSUE TITLE
Use Case 24: Backend Functionality for Monitoring Sensor Data Against Thresholds

### ISSUE THREAD

**Issue by ktageja** [VictorKwong/DataSense-PRJ666-team-5#24]
#   Set Up User Interface for Alert Configuration

## User Story

As a backend developer, I want to implement a system that continuously monitors sensor data against user-defined thresholds so that alerts are triggered when conditions are met.

## Description

This use case involves developing backend functionality that continuously compares incoming sensor data with user-defined thresholds. When the data exceeds thresholds, alerts are triggered, and the user is notified.

## Acceptance Criteria

- Backend checks incoming sensor data against thresholds set by users.
- Alerts are triggered when sensor data exceeds defined limits.
- Each alert occurrence is logged for tracking and debugging.

### Normal Flow of Events

Sensor data is received from the Raspberry Pi.
Backend compares the data to each user’s thresholds.
If data exceeds thresholds, the backend triggers an alert and logs the event.

#### S-1: Missing or corrupted sensor data

Sensor data is received from the Raspberry Pi.
Backend compares the data to each user’s thresholds.
If data exceeds thresholds, the backend triggers an alert and logs the event.

**Comment by VictorKwong** [comment]
Create an /alert page. The alert page will scan through the .csv file to check for threshold levels.

If the threshold is exceeded, it will send a notification to the user.

https://prj666deploy-9xd1.vercel.app/alert
