### ISSUE TITLE
Use Case 25:  : Implement Email Notification System for Alerts

### ISSUE THREAD

**Issue by ktageja** [VictorKwong/DataSense-PRJ666-team-5#25]
#   Implement Email Notification System for Alerts 

## User Story

As a user, I want to receive email notifications when sensor data exceeds my defined thresholds so that I am promptly informed of any critical conditions.

## Description

This use case involves creating an email notification system that sends alerts to users when sensor data exceeds thresholds. The email should include details about the sensor type, threshold exceeded, and current data value.

## Acceptance Criteria

Email notifications are sent to users when an alert is triggered.
The email contains details about the alert: sensor type, threshold value, and current data reading.
The email is sent promptly after an alert is triggered.

### Normal Flow of Events

The backend triggers an alert based on sensor data exceeding thresholds.
The system generates an email with alert details and sends it to the user.
The user receives the email promptly.

#### S-1:   Email fails to send Email fails to send

The system retries sending the email notification if the initial attempt fails.
The backend logs any email sending issues for troubleshooting

**Comment by zhifenli** [comment]
Development of this functionality will continue in Sprint 4.

**Comment by zhifenli** [comment]
Not done yet

**Comment by ktageja** [comment]
going to work on and get it done before live demo

**Comment by ktageja** [comment]
was not able to impkemet email in website
