### ISSUE TITLE
Use Case 28:  Deploy Backend to a Live Server

### ISSUE THREAD

**Issue by ktageja** [VictorKwong/DataSense-PRJ666-team-5#28]
#   Deploy Backend to a Live Server

## User Story
As a developer, I want to deploy the backend server to a live environment so that users can access real-time data and receive alerts and notifications from anywhere.
## Description
This use case involves deploying the backend server to a live production environment, enabling secure access to the system’s features over the internet. This includes setting up the necessary infrastructure, configuring environment variables, ensuring secure connections (HTTPS), and verifying that the live server is functional and accessible.
## Acceptance Criteria
The backend is deployed to a live server, accessible via a secure (HTTPS) URL.
Environment variables for API keys, database URLs, and other sensitive information are securely managed.
Deployment process is automated, using CI/CD pipelines for efficient updates.
The backend can handle incoming sensor data and user requests in real-time on the live server.
Alerts, notifications, and data storage work as expected in the production environment.
### Normal Flow of Events
The developer sets up the live server environment (e.g., AWS, DigitalOcean, or Heroku).
Environment variables are configured securely for production.
CI/CD pipeline is configured to automate deployment upon code changes.
The backend is deployed, and the server is accessible via a live URL.
The developer tests all endpoints to ensure they function correctly in the live environment.
#### S-1:  Server deployment fails due to configuration issues
The developer reviews the deployment logs, identifies the misconfiguration, and redeploys.
#### S-2:  Security and HTTPS setup issues
The server fails to establish a secure HTTPS connection.
The developer sets up an SSL certificate and reconfigures the server for secure communication.
#### S-3:  Environment variable misconfiguration
The backend fails to connect to external services (e.g., database) due to incorrect environment variables.
The developer corrects the variables and redeploys to ensure successful integration.

**Comment by VictorKwong** [comment]
https://github.com/VictorKwong/DataSenseBackEnd-PRJ666-team-5

we are using Render to push our back-end server live:
https://dashboard.render.com/
https://datasensebackend-prj666-team-5.onrender.com/
