### ISSUE TITLE
Use Case 31: Achieve Live Data on Live Server Using a Database

### ISSUE THREAD

**Issue by ktageja** [VictorKwong/DataSense-PRJ666-team-5#31]
#   Achieve Live Data on Live Server Using a Database

## User Story

As a developer, I want to implement live data functionality on the live server so that users can access real-time sensor updates through the deployed platform.

## Description

This use case involves setting up a mechanism to achieve live data updates on the live server, similar to what was implemented on the local server. The goal is to store incoming sensor data in a database and retrieve it in real-time for the dashboard. WebSocket or other real-time communication methods will be integrated to push updates from the server to the frontend.

## Acceptance Criteria

Sensor data is sent from the Raspberry Pi to the live server via HTTP POST.
The live server stores the data in a database (e.g., MongoDB or Firebase) in real time.
The backend retrieves the most recent data from the database and pushes it to the frontend via WebSocket or polling.
Users see real-time data updates on the dashboard without needing to refresh the page.
The system handles high-frequency updates efficiently without performance issues.
### Normal Flow of Events

Raspberry Pi sends sensor data to the live server’s /sensor-data endpoint.
The live server stores the data in the database with timestamps.
The live server pushes the most recent data to the dashboard in real time.
The frontend dashboard updates the displayed sensor data automatically.

#### S-1: Database connection issues
If the live server fails to connect to the database, the system logs the error and retries the connection.
####  S-2: Delays in data retrieval or update

If retrieving or pushing data takes too long, the system implements optimizations (e.g., caching or batch updates).
#### S-3: Large data volume causes performance issues

The system implements strategies to limit data retention (e.g., removing outdated records) or optimize query performance.

**Comment by VictorKwong** [comment]
Built a connect between R-pi Pico and mongoDB. Using wifi hotspot (Maximum compatibility).
