### ISSUE TITLE
Use Case 34: Optimize Database for High-Frequency Data Updates 

### ISSUE THREAD

**Issue by ktageja** [VictorKwong/DataSense-PRJ666-team-5#34]
# Optimize Database for High-Frequency Data Updates

## User Story
As a backend developer, I want to optimize the database to handle high-frequency live sensor data updates so that the system remains performant under heavy load.
## Description

This use case involves optimizing the database to store and retrieve live data efficiently. Indexing, caching, and query optimization techniques will be applied to ensure the database performs well under high-frequency updates from sensors.

## Acceptance Criteria

The database can handle high-frequency updates (e.g., data arriving every second) without significant performance degradation.
Query response times for real-time and historical data remain under acceptable limits (e.g., <500ms).
Indexing is implemented to speed up common queries (e.g., retrieving the latest data).

### Normal Flow of Events

Stress-test the database with high-frequency data writes and reads.
Verify the system’s performance metrics under load.

**Comment by zhifenli** [comment]
The database can handle high-frequency updates (e.g., data arriving every second) without significant performance degradation.
Query response times for real-time and historical data remain under acceptable limits (e.g., <500ms).
Indexing is implemented to speed up common queries (e.g., retrieving the latest data).
